### ISSUE TITLE
How do you add controls?

### ISSUE THREAD

**Issue by jdhnp** [FanTranslatorsInternational/ImGui.Forms#1]
I can run `new Application().Execute(new Form());`, but how do you add controls to the Form?

**Comment by onepiecefreak3** [comment]
As stated in the "Get Started" section, you have to derive from `Form` to add your components. `Form` is an abstract class, so you cannot create an instance from it without derivation. This library was designed to be as design-equal to WinForms as possible. There you also derive from a class `Form` and have a method in it (normally `InitializeComponent()`) which adds the whole tree of components you want.

`Form` has a property `Content` of type `Component`. So you can only add one single component to a form. Adding multiple components to a form, requires you to create one of the layout components.

Example:
```
class MainForm : Form
{
  public MainForm()
  {
    InitializeComponent();
  }

  private void InitializeComponent()
  {
    Content = new Button { Caption = "Test" };
    /* -or- */
    Content = new StackLayout();  // adding multiple components to the layout
  }
}
```

Followed by the application line in your main function:
`new Application().Execute(new MainForm());`

**Comment by onepiecefreak3** [comment]
I also updated the READ.ME to hopefully be more clear about the starting process.
